name: mambaseries
channels:
  - pytorch
  - conda-forge
  - nvidia
  - nodefaults
dependencies:
  - python=3.10
  - pip
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=12.4
  - cuda-toolkit=12.4
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - tqdm
  - wandb
  - hydra-core
  - omegaconf
  - pytorch-lightning
  - einops
  - ipykernel
