#simulate_cellml.py
"""
A minimal standalone example for simulating one CellML model with scipy.

This script loads a *wrapped* CellML model (a Python module generated by
the Physiome-ODE pipeline via OpenCOR + append_all_wrappers.py) and
integrates its ODE system with scipy.integrate.odeint.

Examples
--------
Use a model already stored in SysBio-Traj/Data:
python simulate_cellml.py \
  --model-dir Data/dupont_1991a \
  --model-name dupont_1991a \
  --start-time 0 \
  --end-time 30 \
  --num-timepoints 512

Use the initial_conditions.json file in the same model directory:
python simulate_cellml.py \
  --model-dir Data/dupont_1991a \
  --model-name dupont_1991a \
  --start-time 0 \
  --end-time 30 \
  --num-timepoints 512 \
  --use-ic-json \
  --output scripts/dupont_1991a_simulated.csv

Use a wrapped Python file directly:
python simulate_cellml.py \
  --wrapped-file /path/to/model_wrapped.py \
  --start-time 0 \
  --end-time 100 \
  --num-timepoints 512 \
  --output /path/to/output.csv
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.integrate import odeint


ROOT_DIR = Path(__file__).resolve().parents[0]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Simulate one wrapped CellML model.")

    source_group = parser.add_mutually_exclusive_group(required=True)
    source_group.add_argument(
        "--wrapped-file",
        type=Path,
        help="Path to a *_wrapped.py module.",
    )
    source_group.add_argument(
        "--model-dir",
        type=Path,
        help="Directory containing <model_name>_wrapped.py (and optionally initial_conditions.json).",
    )

    parser.add_argument(
        "--model-name",
        help="Model name used to resolve <model_dir>/<model_name>_wrapped.py.",
    )
    parser.add_argument("--start-time", type=float, required=True, help="Simulation start time.")
    parser.add_argument("--end-time", type=float, required=True, help="Simulation end time.")
    parser.add_argument(
        "--num-timepoints",
        type=int,
        default=512,
        help="Number of sampled time points.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Output CSV path. If omitted, the file is saved in the model directory.",
    )
    parser.add_argument(
        "--ic-json",
        type=Path,
        default=None,
        help="Path to a JSON file containing initial conditions.",
    )
    parser.add_argument(
        "--use-ic-json",
        action="store_true",
        help="Use <model_dir>/initial_conditions.json.",
    )
    return parser.parse_args()


def resolve_wrapped_path(args: argparse.Namespace) -> Path:
    if args.wrapped_file is not None:
        return args.wrapped_file.resolve()

    if not args.model_name:
        raise ValueError("--model-name is required when --model-dir is used.")

    wrapped_path = args.model_dir / f"{args.model_name}_wrapped.py"

    # Fallback: if exact name doesn't exist, use the first *_wrapped.py found
    if not wrapped_path.is_file():
        candidates = list(args.model_dir.glob("*_wrapped.py"))
        if not candidates:
            raise FileNotFoundError(
                f"No *_wrapped.py file found in {args.model_dir}"
            )
        wrapped_path = candidates[0]

    return wrapped_path.resolve()


def resolve_output_path(args: argparse.Namespace, wrapped_path: Path) -> Path:
    if args.output is not None:
        return args.output.resolve()

    if args.model_dir and args.model_name:
        filename = f"{args.model_name}_simulated.csv"
        return (args.model_dir / filename).resolve()

    filename = f"{wrapped_path.stem.replace('_wrapped', '')}_simulated.csv"
    return wrapped_path.with_name(filename).resolve()


def resolve_ic_json_path(args: argparse.Namespace) -> Path | None:
    if args.ic_json is not None:
        return args.ic_json.resolve()

    if args.use_ic_json:
        if not args.model_dir:
            raise ValueError("--use-ic-json can only be used together with --model-dir.")
        return (args.model_dir / "initial_conditions.json").resolve()

    return None


def load_wrapped_module(wrapped_path: Path):
    """Dynamically import a *_wrapped.py file as a Python module."""
    spec = importlib.util.spec_from_file_location("cellml_wrapped", wrapped_path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Could not load module spec from {wrapped_path}")

    module = importlib.util.module_from_spec(spec)
    sys.modules["cellml_wrapped"] = module
    spec.loader.exec_module(module)
    return module


def load_initial_conditions(ic_json_path: Path | None) -> dict:
    """Load an initial-conditions JSON file.

    Accepts two JSON layouts:
      - SysBio-Traj style:   {"initial_conditions": {...}}
      - Physiome-ODE style:  {"states": {...}, "parameters": {...}}
    Returns a dict with keys "states" and "parameters" (either may be empty).
    """
    if ic_json_path is None:
        return {"states": {}, "parameters": {}}

    with ic_json_path.open("r", encoding="utf-8") as f:
        payload = json.load(f)

    if not isinstance(payload, dict):
        raise ValueError(f"Initial-condition JSON must be a dictionary: {ic_json_path}")

    # SysBio-Traj layout: {"initial_time": ..., "initial_conditions": {...}}
    if "initial_conditions" in payload:
        return {
            "states": {str(k): float(v) for k, v in payload["initial_conditions"].items() if v is not None},
            "parameters": {},
        }

    # Physiome-ODE layout: {"states": {...}, "parameters": {...}}
    states = {}
    if "states" in payload:
        states = {str(k): float(v) for k, v in payload["states"].items() if v is not None}

    parameters = {}
    if "parameters" in payload:
        parameters = {str(k): float(v) for k, v in payload["parameters"].items() if v is not None}

    return {"states": states, "parameters": parameters}


def apply_initial_conditions(params, y0: np.ndarray, state_names: list[str], ic: dict) -> np.ndarray:
    """Override parameter values and state initial values from the IC dict.

    Returns the (possibly updated) y0 array.
    """
    # Override parameter constants
    for name, value in ic.get("parameters", {}).items():
        if hasattr(params, name):
            setattr(params, name, value)
        else:
            print(f"Warning: cannot set parameter '{name}', skipped.")

    # Override state initial values
    y0_new = y0.copy()
    for name, value in ic.get("states", {}).items():
        if name in state_names:
            idx = state_names.index(name)
            y0_new[idx] = value
        else:
            print(f"Warning: cannot set state '{name}', skipped.")

    return y0_new


def simulate_cellml(
    wrapped_path: Path,
    output_path: Path,
    start_time: float,
    end_time: float,
    num_timepoints: int,
    ic_json_path: Path | None = None,
) -> Path:
    """Load a wrapped CellML module, integrate its ODEs, and write a CSV."""
    module = load_wrapped_module(wrapped_path)

    # 1. Initialize default parameters and extract state metadata
    params = module.Parameters()
    config = module.Config(param=params, calculate=False)
    y0 = np.asarray(config.y0)
    state_names = config.state_names

    # 2. Apply initial-condition overrides (if any)
    ic = load_initial_conditions(ic_json_path)
    if ic["states"] or ic["parameters"]:
        y0 = apply_initial_conditions(params, y0, state_names, ic)
        # Re-create config with updated params/y0 so pend sees the new constants
        config = module.Config(param=params, calculate=False, y0=list(y0))

    # 3. Integrate with scipy on a uniform time grid
    t = np.linspace(start_time, end_time, num_timepoints)
    trajectory = odeint(config.pend, y0, t)

    # 4. Build DataFrame and write to disk
    df = pd.DataFrame(trajectory, columns=state_names)
    df.insert(0, "time", t)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(output_path, index=False)
    return output_path


def main() -> None:
    args = parse_args()
    wrapped_path = resolve_wrapped_path(args)
    output_path = resolve_output_path(args, wrapped_path)
    ic_json_path = resolve_ic_json_path(args)

    if not wrapped_path.is_file():
        raise FileNotFoundError(f"Cannot find wrapped module: {wrapped_path}")
    if ic_json_path is not None and not ic_json_path.is_file():
        raise FileNotFoundError(f"Cannot find IC JSON file: {ic_json_path}")

    saved_path = simulate_cellml(
        wrapped_path=wrapped_path,
        output_path=output_path,
        start_time=args.start_time,
        end_time=args.end_time,
        num_timepoints=args.num_timepoints,
        ic_json_path=ic_json_path,
    )
    print(f"Saved to: {saved_path}")


if __name__ == "__main__":
    main()
